name: YARF Snap - Software Bill of Materials (SBOM)
on:
  pull_request:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

permissions:
  contents: read  # Required to check out repository code

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sbom:
    name: YARF Snap - Software Bill of Materials (SBOM)
    runs-on:
      - self-hosted-linux-amd64-noble-private-endpoint-medium
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y \
            git-lfs

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          lfs: true
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: "3.12"

      - name: Install python dependencies
        run: |
          pip install requests

      - name: Request and retrieve SBOM
        id: sbom
        env:
          SBOM_SCRIPT_PATH: .github/scripts/sbom/sbom.py
          YARF_CHANNEL: latest/beta
        run: python3 -u ${SBOM_SCRIPT_PATH} --channel=${YARF_CHANNEL}

      - name: Collect SBOM
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: yarf-${{ steps.sbom.outputs.revision }}-sbom
          path: /tmp/yarf-${{ steps.sbom.outputs.revision }}.sbom.json
          retention-days: 5
