name: TICS Code Quality Analysis
on:
  schedule:
    - cron: '00 19 * * *'
  workflow_dispatch:

permissions:
  contents: read  # Required to check out repository code

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    name: Run TICS analysis
    runs-on: [self-hosted-linux-amd64-noble-tiobe]
    steps:
      - name: Install dependencies
        run: |
            sudo apt update -qq
            sudo apt install -y \
            git-lfs \
            libgl1 \
            libxkbcommon-dev \
            jq \
            clang \
            python3-tk

            pip install uv --break-system-packages

      - name: Checkout repo (main branch)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: main
          lfs: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true

      - name: Install YARF
        run: |
          uv venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          pip install .
          pip install .[develop]

      - name: Run test and coverage
        run: |
          uvx tox

      - name: Rename coverage report for TICS
        run: |
          mkdir ./coverage
          mv ./coverage.xml ./coverage/cobertura.xml

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@427ef84d84bf35e39235d61406f414811bb99ce9
        with:
          mode: qserver
          project: yarf
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          calc: ALL
