name: YARF Snap - Vulnerability Scanning
on:
  workflow_call:
    inputs:
      CHANNEL:
        description: 'YARF snap channel (e.g., latest/stable)'
        type: string
        default: latest/stable
        required: true
      SSDLC_CYCLE:
        description: 'SDLC cycle for the scan (e.g., 25.10, 26.04)'
        type: string
        default: "25.10"
        required: true

  workflow_dispatch:
    inputs:
      CHANNEL:
        description: 'YARF snap channel (e.g., latest/stable)'
        type: string
        default: latest/stable
        required: true
      SSDLC_CYCLE:
        description: 'SDLC cycle for the scan (e.g., 25.10, 26.04)'
        type: string
        default: "25.10"
        required: true

permissions:
  contents: read  # Required to check out repository code

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vulnerability-scan:
    name: YARF Snap - Vulnerability Scanning
    runs-on:
      - self-hosted-linux-amd64-noble-private-endpoint-medium
    steps:
      - name: Install YARF
        run: |
          sudo snap install yarf --channel=${{ inputs.CHANNEL }}

      - name: Install canonical-secscan-client
        run: |
          sudo snap install canonical-secscan-client

      - name: Scan YARF snap for vulnerabilities
        run: |
          SNAP_VERSION=$(snap info "yarf" | awk -v chan="${{ inputs.CHANNEL }}" '$1 == chan":" { print $2 }')
          secscan-client submit \
            --ssdlc-product-name YARF \
            --ssdlc-product-version $SNAP_VERSION \
            --ssdlc-product-channel ${{ inputs.CHANNEL }} \
            --ssdlc-cycle ${{ inputs.SSDLC_CYCLE }} \
            --scanner trivy \
            --token ~/snap/canonical-secscan-client/common/secscan.token \
            --wait-and-print \
            --type package \
            --format snap \
            yarf

      - name: Get Vulnerability Scan Result
        id: vuln-result
        run: |
          secscan-client result \
            --token ~/snap/canonical-secscan-client/common/secscan.token \
            --raw \
            > /tmp/yarf-${{ inputs.CHANNEL }}-${{ inputs.SSDLC_CYCLE }}-vulnerabilities-scan-result.json

      - name: Retrieve Vulnerability Scan Result
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: yarf-${{ inputs.CHANNEL }}-${{ inputs.SSDLC_CYCLE }}-vulnerabilities-scan-result
          path: /tmp/yarf-${{ inputs.CHANNEL }}-${{ inputs.SSDLC_CYCLE }}-vulnerabilities-scan-result.json
          retention-days: 5
