name: YARF Snap - Vulnerability Scanning
on:
  workflow_call:
    inputs:
      CHANNEL:
        description: 'YARF snap channel (e.g., latest/stable)'
        type: string
        default: latest/stable
        required: true
      SSDLC_CYCLE:
        description: 'SDLC cycle for the scan (e.g., 26.04, 26.10)'
        type: string
        default: "26.04"
        required: true

  pull_request:
  workflow_dispatch:
    inputs:
      CHANNEL:
        description: 'YARF snap channel (e.g., latest/stable)'
        type: string
        default: latest/stable
        required: true
      SSDLC_CYCLE:
        description: 'SDLC cycle for the scan (e.g., 26.04, 26.10)'
        type: string
        default: "26.04"
        required: true

permissions:
  contents: read  # Required to check out repository code

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vulnerability-scan:
    name: YARF Snap - Vulnerability Scanning
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    runs-on:
      - self-hosted-linux-amd64-noble-private-endpoint-medium
    steps:
      - name: Install canonical-secscan-client
        run: |
          sudo snap install canonical-secscan-client

      - name: Scan YARF snap for vulnerabilities
        env:
          # TARGET_CHANNEL: ${{ inputs.CHANNEL }}
          # TARGET_SSDLC_CYCLE: ${{ inputs.SSDLC_CYCLE }}
          TARGET_CHANNEL: latest/beta
          TARGET_SSDLC_CYCLE: "26.04"
          ARCH: ${{ matrix.arch }}
        run: |
          SNAP_VERSION=$(snap info "yarf" | awk -v chan="$TARGET_CHANNEL" '$1 == chan":" { print $2 }')
          SNAP_CHANNEL=$(echo "$TARGET_CHANNEL" | cut -d'/' -f2)
          secscan-client submit \
            --ssdlc-product-name YARF \
            --ssdlc-product-version $SNAP_VERSION \
            --ssdlc-product-channel $SNAP_CHANNEL \
            --ssdlc-cycle $TARGET_SSDLC_CYCLE \
            --scanner trivy \
            --token ~/snap/canonical-secscan-client/common/secscan.token \
            --type package \
            --format snap \
            --wait-and-print \
            yarf/$SNAP_CHANNEL@$ARCH

      - name: Get Vulnerability Scan Result
        id: vuln-result
        env:
          # TARGET_CHANNEL: ${{ inputs.CHANNEL }}
          # TARGET_SSDLC_CYCLE: ${{ inputs.SSDLC_CYCLE }}
          TARGET_CHANNEL: $(echo "latest/beta" | cut -d'/' -f2)
          TARGET_SSDLC_CYCLE: "26.04"
        run: |
          secscan-client result \
            --token ~/snap/canonical-secscan-client/common/secscan.token \
            --raw \
            > /tmp/yarf-$TARGET_CHANNEL-$TARGET_SSDLC_CYCLE-vulnerabilities-scan-result.json

      - name: Retrieve Vulnerability Scan Result
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        env:
          # TARGET_CHANNEL: ${{ inputs.CHANNEL }}
          # TARGET_SSDLC_CYCLE: ${{ inputs.SSDLC_CYCLE }}
          TARGET_CHANNEL: $(echo "latest/beta" | cut -d'/' -f2)
          TARGET_SSDLC_CYCLE: "26.04"
          ARCH: ${{ matrix.arch }}
        with:
          name: yarf-$TARGET_CHANNEL-$ARCH-$TARGET_SSDLC_CYCLE-vulnerabilities-scan-result
          path: /tmp/yarf-$TARGET_CHANNEL-$ARCH-$TARGET_SSDLC_CYCLE-vulnerabilities-scan-result.json
          retention-days: 5
